/* Authoring build only; index.html requires no dependencies at runtime. */
const fs = require('fs');
const path = require('path');
let Marp;
try { ({Marp}=require('@marp-team/marp-core')); }
catch { ({Marp}=require('../../tmp/preeclampsia-tools/node_modules/@marp-team/marp-core')); }
const marp = new Marp({html:true,inlineSVG:false});
marp.themeSet.add(fs.readFileSync(path.join(__dirname,'theme.css'),'utf8'));
const result = marp.render(fs.readFileSync(path.join(__dirname,'slides.md'),'utf8'));
result.html = result.html.replace(/<section id="(\d+)"/g, '<section id="slide-$1"');
const shellCss = `
html,body{margin:0;min-height:100%;background:#07121f;color:#edf5ff;font-family:Arial,sans-serif}body{height:100vh;display:flex;flex-direction:column;overflow:hidden}*{box-sizing:border-box}.toolbar{min-height:74px;padding:12px 22px;display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid #294357;background:#0c1c2b;z-index:5}.brand{font-size:17px;font-weight:bold;letter-spacing:1px;color:#67e8f9}.actions{display:flex;align-items:center;gap:10px}button,select,.tool-link{font:14px Arial;color:#edf5ff;background:#152c40;border:1px solid #496578;border-radius:8px;padding:9px 11px;cursor:pointer}.tool-link{text-decoration:none}button:disabled{opacity:.45;cursor:default}button:focus-visible,select:focus-visible,a:focus-visible,summary:focus-visible{outline:3px solid #ffcb80;outline-offset:3px}select{max-width:260px}.stage{flex:1;position:relative;min-height:0;display:flex;align-items:center;justify-content:center;overflow:hidden}.marpit{width:1280px;height:720px;flex-shrink:0;transform:scale(var(--scale,1));transform-origin:center}.marpit>section{margin:0!important}.marpit>section[hidden]{display:none!important}.nav{display:flex;justify-content:center;align-items:center;gap:15px;padding:10px 18px;background:#0c1c2b;min-height:59px}#counter{min-width:95px;text-align:center;font-size:14px}.progress{height:4px;background:#233d52}.progress>div{height:100%;width:0;background:#22d3ee;transition:width .15s}dialog{color:#edf5ff;background:#10263a;border:1px solid #5c8096;border-radius:16px;padding:28px;max-width:800px;width:calc(100% - 32px);max-height:85vh;overflow:auto}dialog::backdrop{background:#000a}dialog h2{font-size:25px}dialog a{color:#67e8f9}dialog li{font-size:16px;line-height:1.5;margin:12px 0}dialog .close{float:right}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.skip{position:absolute;top:-100px;left:12px;z-index:50;background:#fff;color:#000;padding:10px}.skip:focus{top:8px}noscript{display:block;background:#472e23;padding:12px}body.no-js{height:auto;overflow:auto}body.no-js .stage{display:block}body.no-js .marpit{height:auto;width:auto;transform:none}body.no-js .marpit>section{margin:15px auto!important}body.no-js .nav{display:none}
@media(max-width:760px){body{height:100dvh}.toolbar{padding:10px 12px;flex-wrap:wrap;gap:8px}.brand{font-size:15px}.actions{width:100%;gap:6px;flex-wrap:wrap}button,select,.tool-link{font-size:12px;padding:8px}select{max-width:none;flex:1;min-width:90px}.stage{display:block;overflow:auto}.marpit{transform:none!important;width:100%;height:auto}.marpit>section{width:100%!important;height:auto!important;min-height:calc(100dvh - 179px);padding:25px 22px 38px!important;font-size:19px!important;overflow:visible!important}.marpit>section h1{font-size:32px!important;letter-spacing:-.8px;margin:14px 0 22px}.marpit>section h2{font-size:23px!important}.marpit>section .eyebrow{font-size:12px!important;letter-spacing:1.5px}.marpit>section .lead{font-size:23px!important}.marpit>section .grid,.marpit>section .flow{grid-template-columns:1fr!important;gap:12px}.marpit>section .card,.marpit>section .flow>div{padding:17px}.marpit>section .card p,.marpit>section .card li,.marpit>section .flow p{font-size:19px!important}.marpit>section .flow strong{font-size:22px!important}.marpit>section .takeaway{font-size:20px!important;margin-top:20px}.marpit>section .source{font-size:13px!important;padding-top:18px}.marpit>section .small{font-size:17px!important}.marpit>section .credit{font-size:17px!important}.marpit>section .pearls li{font-size:21px!important}.marpit>section .ref-list li{font-size:17px!important}.marpit>section .dose strong{font-size:48px!important}.marpit>section .dose span{font-size:18px!important}.marpit>section::after{display:none!important}.nav{padding:8px;min-height:49px}.marpit>section details p{font-size:18px!important}.marpit>section summary{font-size:19px!important}}
@media(prefers-reduced-motion:reduce){*{transition:none!important;scroll-behavior:auto!important}}
@media print{@page{size:13.333in 7.5in;margin:0}html,body{background:white;height:auto;display:block;overflow:visible}.toolbar,.nav,.progress,.skip,.sr-only,dialog,noscript{display:none!important}.stage{display:block;height:auto;overflow:visible}.marpit{width:1280px;height:auto;transform:none!important}.marpit>section,.marpit>section[hidden]{display:flex!important;width:1280px!important;height:720px!important;min-height:0!important;padding:52px 64px 50px!important;break-after:page;page-break-after:always;margin:0!important;print-color-adjust:exact;-webkit-print-color-adjust:exact}.marpit>section:last-child{break-after:auto;page-break-after:auto}.marpit>section details>p{display:block!important}.marpit>section details summary{list-style:none}.marpit>section .grid.two{grid-template-columns:repeat(2,minmax(0,1fr))!important}.marpit>section .grid.three,.marpit>section .flow{grid-template-columns:repeat(3,minmax(0,1fr))!important}.marpit>section .flow.four{grid-template-columns:repeat(4,minmax(0,1fr))!important}a{overflow-wrap:anywhere}}
`;
const js = `
document.body.classList.remove('no-js');
const slides=[...document.querySelectorAll('.marpit>section')],total=slides.length,stage=document.querySelector('.stage'),chooser=document.querySelector('#chooser'),dialog=document.querySelector('#references');let current=0,touch=null;
slides.forEach((s,i)=>{s.id='slide-'+(i+1);s.setAttribute('role','group');s.setAttribute('aria-roledescription','slide');s.setAttribute('aria-label',(i+1)+' of '+total+': '+s.querySelector('h1').textContent);s.tabIndex=-1;const o=new Option((i+1)+'. '+s.querySelector('h1').textContent,String(i));chooser.add(o)});
document.querySelectorAll('.ref-list').forEach(x=>dialog.querySelector('.reference-body').append(x.cloneNode(true)));
function fit(){const box=stage.getBoundingClientRect();document.querySelector('.marpit').style.setProperty('--scale',Math.min((box.width-24)/1280,(box.height-12)/720,1.5))}
function hashIndex(){const m=location.hash.match(/^#slide-(\\d+)$/);return m?Math.max(0,Math.min(total-1,Number(m[1])-1)):0}
function show(i,focus=false){current=Math.max(0,Math.min(total-1,i));slides.forEach((s,n)=>s.hidden=n!==current);chooser.value=String(current);document.querySelector('#counter').textContent=(current+1)+' / '+total;document.querySelector('#progress-fill').style.width=((current+1)/total*100)+'%';document.querySelector('#progress').setAttribute('aria-valuenow',current+1);document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===total-1;document.querySelector('#status').textContent='Slide '+(current+1)+' of '+total+': '+slides[current].querySelector('h1').textContent;if(location.hash!=='#slide-'+(current+1))history.replaceState(null,'','#slide-'+(current+1));stage.scrollTop=0;if(focus)slides[current].focus({preventScroll:true});fit()}
document.querySelector('#prev').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);chooser.onchange=()=>show(Number(chooser.value));document.querySelector('#refs').onclick=()=>dialog.showModal();document.querySelector('#close-refs').onclick=()=>dialog.close();document.querySelector('#print').onclick=()=>window.print();window.addEventListener('hashchange',()=>show(hashIndex(),true));window.addEventListener('resize',fit);
document.addEventListener('keydown',e=>{if(dialog.open||e.altKey||e.ctrlKey||e.metaKey||/INPUT|SELECT|TEXTAREA|SUMMARY|BUTTON|A/.test(e.target.tagName))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();show(current+1,true)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(current-1,true)}else if(e.key==='Home'){e.preventDefault();show(0,true)}else if(e.key==='End'){e.preventDefault();show(total-1,true)}});
stage.addEventListener('touchstart',e=>{if(e.target.closest('a,button,summary,details'))return;touch=[e.changedTouches[0].clientX,e.changedTouches[0].clientY]},{passive:true});stage.addEventListener('touchend',e=>{if(!touch)return;const dx=e.changedTouches[0].clientX-touch[0],dy=e.changedTouches[0].clientY-touch[1];touch=null;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.5)show(current+(dx<0?1:-1),true)},{passive:true});show(hashIndex());
`;
const title='Preeclampsia Prevention - A Shared Plan for Patients and Providers';
const desc='Patient education and provider guidance based on Nadia Kendrick’s doctoral quality improvement project, with printable chart checklists and a de-identified audit worksheet.';
const seo={"@context":"https://schema.org","@type":"MedicalWebPage",name:title,description:desc,url:'https://openmfm.org/decks/preeclampsia-prevention-kendrick/index.html',publisher:{'@type':'Organization',name:'OpenMFM',url:'https://openmfm.org'},author:{'@type':'Organization',name:'OpenMFM'},creditText:'Project source: Nadia Kendrick, MSN, FNP-BC, DNP student, Georgia Southern University',dateModified:'2026-09-30',inLanguage:'en',audience:{'@type':'MedicalAudience',audienceType:'Patients and prenatal care providers'}};
const out=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title>
<!-- openmfm-seo-injected -->
<meta name="description" content="${desc}"><meta name="author" content="OpenMFM; project source: Nadia Kendrick, MSN, FNP-BC"><link rel="canonical" href="${seo.url}"><meta property="og:type" content="website"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><meta property="og:url" content="${seo.url}"><meta property="og:site_name" content="OpenMFM"><meta property="og:image" content="https://openmfm.org/og-image.png"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify(seo)}</script><style>${result.css}\n${shellCss}</style></head>
<body class="no-js"><a class="skip" href="#slide-1">Skip to slides</a><header class="toolbar"><!-- openmfm-footer-injected --><a class="brand" href="https://openmfm.org/library" aria-label="OpenMFM library">OpenMFM / Prevention</a><nav class="actions" aria-label="Presentation tools"><select id="chooser" aria-label="Choose slide"></select><button id="refs">References</button><a class="tool-link" href="resources/chart-checklist.pdf">Chart form</a><button id="print">Print / PDF</button></nav></header><noscript>JavaScript is disabled. All slides are shown below. Use your browser's print function to save a PDF.</noscript><main class="stage" aria-label="Preeclampsia prevention slides">${result.html}</main><div id="status" class="sr-only" role="status" aria-live="polite"></div><nav class="nav" aria-label="Slide navigation"><button id="prev" aria-label="Previous slide">← Previous</button><span id="counter"></span><button id="next" aria-label="Next slide">Next →</button><span class="sr-only">Arrow keys navigate slides; swipe horizontally on touch screens.</span></nav><div class="progress" id="progress" role="progressbar" aria-label="Presentation progress" aria-valuemin="1" aria-valuemax="${result.comments.length || 26}"><div id="progress-fill"></div></div><dialog id="references" aria-labelledby="reference-title"><button class="close" id="close-refs">Close</button><h2 id="reference-title">References</h2><div class="reference-body"></div><p><a href="resources/chart-checklist.pdf">Chart checklist</a> · <a href="resources/audit-worksheet.pdf">Audit worksheet</a> · <a href="resources/workflow-guide.md">Paper workflow guide</a></p></dialog><script>${js}</script></body></html>`;
fs.writeFileSync(path.join(__dirname,'index.html'),out);
console.log('Rendered MARP HTML. Slides:',result.comments.length,'HTML bytes:',Buffer.byteLength(out));
